### ISSUE TITLE
FastAPI version requirements? Doesn't install with latest

### ISSUE THREAD

**Issue by thebleucheese** [jordanisaacs/fastapi-sessions#10]
First, thanks for writing this, it's great to have sessions support for FastAPI!

I'm trying to install with the latest version of FastAPI and getting the following message:
"Because fastapi-sessions (0.3.0) depends on fastapi (>=0.65.1,<0.66.0)
   and no versions of fastapi-sessions match >0.3.0,<0.4.0, fastapi-sessions (>=0.3.0,<0.4.0) requires fastapi (>=0.65.1,<0.66.0)."

Any chance you can loosen the version requirements?
Changing the line in the pyproject.toml to: 
`fastapi = "^0.65"`
might fix it

**Comment by command-tab** [comment]
Yes please! I'm unable to install this alongside FastAPI `0.68.1`

**Comment by jordanisaacs** [comment]
Should be fixed with latest update fastapi-sessions `0.3.2`
