### ISSUE TITLE
httpx dependency

### ISSUE THREAD

**Issue by tanglisha** [jordanisaacs/fastapi-sessions#13]
Hello! Would you please add the `httpx` package as a dependency in the documentation? I got an error that it was missing when I tried to run the example.

Thanks for making this, I'm having fun with it!

**Comment by jordanisaacs** [comment]
Are you still having this issue? I was testing the example and it does not ask for `httpx`. My guess is it has to do with a dependency of `fastapi` itself.

**Comment by rauberdaniel** [comment]
Works fine for me without `httpx`, so I guess it’s not actually a necessary dependency.

**Comment by jordanisaacs** [comment]
I will close this issue for now. @tanglisha let me know if you still have any issues and I will reopen it.
