### ISSUE TITLE
Correct Usage

### ISSUE THREAD

**Issue by clayscode** [jordanisaacs/fastapi-sessions#15]
Does the Depends(Verifier) bit have to be included on every single endpoint? Or can that be included at the router level?

**Comment by jordanisaacs** [comment]
The code behind Depends(Verifier) is a normal dependency with the only requirement being that Depends(Frontend) occurs first. Therefore this code works:

```python
router = APIRouter(
    prefix = "/items",
    dependencies = [ Depends(cookie), Depends(verifier) ]
)
```

But this would fail.

```python
router = APIRouter(
    prefix = "/items",
    dependencies = [ Depends(verifier), Depends(cookie) ]
)
```

You would not have access to the `SessionData` though by default. You would have to look into returning a value from a global dependency.
