### ISSUE TITLE
Base Use-case Example

### ISSUE THREAD

**Issue by wightman** [jordanisaacs/fastapi-sessions#2]
I'm game to give this a try with a very simple api I'm developing, but would benefit from a simple example of instantiating the session and protecting an endpoint with just the default backend.

**Comment by jordanisaacs** [comment]
Hi! I just rewrote a lot of the backend code to make it stable and also implemented the logic for CSRF tokens. You will notice that a second cookie name+"csrf" gets created when testing out the API that you don't have any control over. Just ignore it as its a placeholder.

The latest version is up on pip as version 0.2.0. I am interested in your feedback on how the experience is with using it and what features you are interested in. Please note I would not recommend this for anything public facing at the moment as it isn't secure until CSRF is finished being implemented.

To use it you want to generate a secret key, the name will be the key value of the cookie, the scheme_name is what shows up in the API docs, the backend is how the data is stored, auto_error is whether to return None or raise an HTTP exception, and a data model that verifies the associated session data. You can also set any parameters to the cookies as in Starlette. Here is a test app I have been using:

```python
from typing import Tuple, Optional, Any

from pydantic import BaseModel
from fastapi import FastAPI, Depends, Response, HTTPException

from fastapi_sessions import SessionCookie, SessionInfo
from fastapi_sessions.backends import InMemoryBackend

test_app = FastAPI()

class SessionData(BaseModel):
    username: str


class BadSessionData(BaseModel):
    fakename: str


test_session = SessionCookie(
    name="session",
    secret_key="helloworld",
    backend=InMemoryBackend(),
    data_model=SessionData,
    scheme_name="Test Cookies",
    auto_error=False
)


@test_app.get("/secure")
async def secure_thing(session_data: Optional[SessionInfo] = Depends(test_session)):
    if session_data is None:
        raise HTTPException(
            status_code=403,
            detail="Not authenticated"
        )
    return {"message": "You are secure", "user": session_data}

@test_app.post("/get_session")
async def login(username: str, response: Response, session_info: Optional[SessionInfo] = Depends(test_session)):
    old_session = None
    if session_info:
        old_session = session_info[0]
    
    test_user = SessionData(username=username)
    await test_session.create_session(test_user, response, old_session)
    return {"message": "You now have a session", "user": test_user}

@test_app.post("/leave_session")
async def logout(response: Response, session_info: Optional[SessionInfo]  = Depends(test_session)):
    if not session_info:
        raise HTTPException(
            status_code=403,
            detail="Not authenticated"
        )
    await test_session.end_session(session_info[0], response)
    return {"message": "You now don't have a session", "user": session_info}
```

**Comment by jordanisaacs** [comment]
@wightman I threw up a getting started doc that may interest you for simple instantiation and protecting an endpoint. Much more fleshed out then that code blob I put up earlier. https://jordanisaacs.github.io/fastapi-sessions/guide/getting_started/

**Comment by wightman** [comment]
Success!
I did run into an issue with 
   `backend = InMemoryDB()`
in the Session Backend section, but it isn't in the final code.

Thanks for the promptness.

**Comment by jordanisaacs** [comment]
Great to hear! Yes, I am pretty much rewriting the entire library every day as I see new needs arise. So bugs are not exactly what I am worried about. I do believe I am nearing a nice first version design at which point I will start focusing on bug squashing, testing, and detailed documentation. 

If you could provide any details on what your use case for sessions would be that would be very helpful!

**Comment by wightman** [comment]
This is a really small-scope (single-table crud) project that has less than
ten users, all with the same authorizations. On successful login (basic
auth) I generate a session token with their user data (name and id). On
logout I want to remove the session. All endpoints are secure, so the
session is checked on each access and the info retrieved. Really what
you've made to date is everything I need.

Let me know if there's anything I can clarify.
