### ISSUE TITLE
Other backends and questions

### ISSUE THREAD

**Issue by shazz** [jordanisaacs/fastapi-sessions#5]
Hi Jordan,

I was wondering if you were still working on this cool project. I'm using it without problem for a while now, combined with some other code to manage tokens and role.

During development, as I'm using the `--reload` capability from `uvicorn`, the session is obviously always resetted so I tried to implement a persistent backend but I was not able to successfully persist the session (CPyhon errors). So would be nice at least for development to get a simple persisted backend.

Moreover, I'm not sure I fully understand the session configuration (the TO DO did not help :D):

```python
session = SessionCookie(
    name = "session",
    secret_key = str(SESSION_SECRET),
    backend = InMemoryBackend(),
    data_model = SessionData,
    scheme_name = "Server Cookies",
    auto_error = False
)
```
- is there other type of session? What SessionCookie imply?
- what is the usage for `name`? `scheme_name` ? auto_error ?

in the login api:
```python
@test_app.post("/get_session")
async def login(username: str, response: Response, session_info: Optional[SessionInfo] = Depends(test_session)):
    old_session = None
    if session_info:
        old_session = session_info[0]

    test_user = SessionData(username=username)
    await test_session.create_session(test_user, response, old_session)
    return {"message": "You now have a session", "user": test_user}
```

What is the goal if the old_session stuff?
and in `create_session`, response is None no?

Thanks! Really helpful library in anycase!

**Comment by dura-me** [comment]
Hi Jordan,

It was nice and simple. I am not a developer but do coding as a hobby. I tried your example and could immediately got the desired results. Thanks for the effort.
I am trying a small app. In it, I tried to implement your get_session and then give output using HTMLResponse and generate a html page, but unsuccessful.. If you can put an example for that, it would really help me.

```
@app.post("/get_session2", response_class=HTMLResponse)
async def login2(response: Response, request = Request, username: str = Form(...), inputPassword: str = Form(...), session_info: Optional[SessionInfo] = Depends(dura_session)):
    user_authenticated, auth_message, cur_user = authapp.dura_authenticate_user(username, inputPassword)
    if user_authenticated:
        old_session = None
        if session_info:
            old_session = session_info[0]
    
        test_user = SessionData(username=username)
        
        await dura_session.create_session(test_user, response, old_session)
        #return {"message": "You now have a session", "user": test_user}
        return templates.TemplateResponse('welcome.html', context = {"request": request, 'auth_message': auth_message,'welcome_text':'Welcome'})
    else:
        return RedirectResponse('/user/login?auth_message=Require authentication', status_code = status.HTTP_302_FOUND)
```

This is where I am. If i try to return template, session is not created. This got me puzzled.

**Comment by jordanisaacs** [comment]
Hi, sorry for the slow response. Been extremely busy personally the last month. Check out this [issue](https://github.com/jordanisaacs/fastapi-sessions/issues/7) for a general response and goals for a rewrite.
