### ISSUE TITLE
Rewrite and Other Frontends Discussion

### ISSUE THREAD

**Issue by jordanisaacs** [jordanisaacs/fastapi-sessions#7]
Hi all! Sorry for the slow response, been extremely busy personally this past month. There are more people than I expected using this little library for sessions. The current internals were a quick afternoon hack so there are definitely a lot of issues currently as you all have noted. Before I restart the rewrite to bring it to a stable state I want to hear your thoughts on what you want from the library. I had some ideas about the front end, but feel free to respond with any suggestions.

**Frontends**

Right now there is only `SessionCookie`. This is not always good for something like an API. In order for multiple frontends to work with FastAPI autodocs there would need to be a post-processing function as I don't believe there is support for multiple authentication (OR)[[1](https://swagger.io/docs/specification/authentication/api-keys/)]. I am imagining setting up a class called `SessionManager` where you can toggle different types of ApiKeys [[1](https://swagger.io/docs/specification/authentication/api-keys/)]. So either URL/Header/Cookie. Would you like the backends for each frontend type if multiple are enabled to be separated or the same?

**Comment by shazz** [comment]
Hey @jordanisaacs , I'll do that asap!

**Comment by jordanisaacs** [comment]
# Goals

This is fast mockup of what the high level interaction with the rewrite will be. Basic setup and how it works.

## Frontend

### `SessionManager`

This is a single class that is used in dependency injection. Can enable/disable different session types (header/query/cookie). This method will require postprocessing of the OpenAPI schema that FastAPI generates. What the OpenAPI will look like:
```
securitySchemes:
	ApiKeyAuth1: # arbitrary name for security scheme
		type: apiKey
		in: header | query | cookie
		name: SessionName # name of header, query, cookie

security:
	- ApiKeyAuth1: [] # including the - makes it OR
	- ApiKeyAuth2: []
```

A session has data connected to the given ID. The data model is passed into `SessionManager` as a Pydantic data model. Additionally each backing data has a data wrapper. When verifying sessions, only looks at session IDs of the same type `type`

Note: `csrf_token` is now missing. While necessary for security, I decided this is out of scope of sessions. Should be provided by its own library.

```python
class SessionTypeEnum(str, Enum):
	cookie = 'cookie'
	header = 'header'
	url = 'url'

class SessionDataWrapper(GenericModel, Generic[SessionData]):
	data: SessionData
	id: UUID
	type: SessionTypeEnum
	issue_date: datetime
	refresh_date: datetime
	expiration_date: datetime
```

`SessionManager` setup requires frontend configs, a backend, and a data model. Have to enable at least one frontend. Note that the SessionData is both a Type and a parameter. This is to enable type checking and runtime validation. I have not found a  way to retrieve an instance from a generic type.

```python
class SessionManager(Generic[SessionData]):
	def __init__(
		self,
		name: str,
		secret_key: Optional[str], # optional secret key for signing ID (recommended)
		max_age: Optional[int], # max age of sessions in seconds. None if forever
		data_model: Type[SessionData],
		backend: SessionBackend,
		cookie_config: Optional[CookieConfig] = None,
		api_name: Optional[str] = None
		url_name: Optional[str] = None
		scheme_name: Optional[str] = None
		auto_error: bool = False # Automatically raise error or pass error
	):
		# initialize
	
	async def __call__(self, request: Request):
		# authenticate the request

	
@app.get("/")
async def auth_get (session = Depends(SessionManager)):
    pass
```

#### `SessionCookieConfig`

Identify ID using a cookie. Manager copies the config to prevent any changes. Configuration:

```python
class SessionCookieConfig():
	def __init__(
		self,
		name: Optional[str], # inherit name from manager
		path: str = "/",
		domain: str = None,
		secure: bool = False,
		httponly: bool = True,
		samesite: str = "lax"
	)
```

#### `SessionHeaderConfig`

No configuration except passing in the header name to manager

#### `SessionURLConfig`

No configuration except passing in the url parameter name to manager

# Backend

Abstract backend functions still TBD

**Comment by jordanisaacs** [comment]
completed with #9 . frontends/backends/verifiers all setup
