### ISSUE TITLE
Upgrade Fastapi required version due to CVE

### ISSUE THREAD

**Issue by shazz** [jordanisaacs/fastapi-sessions#8]
Hi,

Sorry I did not find the time to properly answer your question.
In the meantime could you upgrade your deps to latest FastAPI, there was a CVE on versions <= 0.65.1 and my Github bot is not happy. (https://github.com/tiangolo/fastapi/releases/tag/0.65.1)

````
[tool.poetry.dependencies]
python = ">=3.6"
fastapi = "^0.63.0"
itsdangerous = "^1.1.0"
````

thanks !

**Comment by jordanisaacs** [comment]
Fixed with the rewrite #9
